apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv-prometheus
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: efs-sc
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-003752b5f68a3f50b::fsap-0936f31435764a8a7
    volumeAttributes:
      encryptInTransit: "true"