apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cert-manager-external-secret
  namespace: cert-manager
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: aws-secretstore
    kind: SecretStore
  target:
    name: aws-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: TERRAFORM_USER_CRED
