# values.yaml
image:
  repository: 571207880192.dkr.ecr.us-east-1.amazonaws.com/fpt-flask-app
  tag: ff8f02c

service:
  - name: fpt-flask-redis-app
    port: 5000
    hostname: fpt.jendyjasper.com
    label: fpt-flask-app
    targetPort: 5000
  - name: game-2048
    port: 80
    hostname: adaugo.jendyjasper.com
    label: game-2048
    targetPort: 80
  - name: fpt-redis
    port: 6379
    hostname: ""
    label: fpt-redis
    targetPort: 6379

game:
  label: game-2048
fpt:
  label: fpt-flask-app
redis:
  label: fpt-redis