---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-secret
  namespace: default
spec:
  encryptedData:
    access-key-id: AgAiTESqPhnRBEWZiGZaZlsiNcLmF4IVhA4MmfUC85ljGF3XPQuI0OahmixwVHmt7Ec6Q2tda2FQDQFD0Qwgd4BSH1Oy/BRoSzXqjaFzwtYwCF3ksUUUv3I0foGfPfUhkQc4Bvk5vqFjT0C6TbKvOee+0MWcIsQt9aVI31yTrhDP4SkWUjRQkAWXuwq8z/imP7OM3OIU2pPuLuHhKGv7ykdyYWv5aoy1sHd96Glvx9QQ8UQ2J2UdW5s10E49bVM9RcGPz3XTsut+wkz9AvwcAqu3HJCfGu57mAPrED4ZalkQv3tUOzkZCKIDE658n/e0/Wge2+v5rm4JYNyHPdthFEKJGeMeTjrYerVHnQJOSPbYlkPg0BhQJPxSy5/h+UfmfU1KZ6PUOP1NO6+D9rtOAQS3rZZhrJSqiZscc8YuqQER610jSpx4ZJVAY/uqDGeMyKY2WFouDGklYZUYlNFp7e4Y2F8tX0kZDexBrKJ5hhY4Mq5QeOfCwQ9LIGYBDh7lxAHEpnVoHSF34XMaQQMIxzB0VHaK5QXy+j10IZ/Nxgo5d/jqaM/xsphQWSIEJdI4N5Dm7+0VPjc0xkZPcsT3pxYCi9EgUlPbH1bdok+C1LkcqfNUNK8CZ5on1q+VPFJozUsXyw1M5h4NjfKzctNfaV016jyehN75IX7Wp7uSy8lJ49v1lJA5D/1nRI/Z5WvYfUa/H52BW7m7ppcGQxuN5gG+w7yWQ6E=
    secret-access-key: AgA2l/jDftuQmeiuftFNnWYyYVDmqqWFQHjBDV1K38UBNdEJvl+0oTE+U+4VhqMAtW3fHN+JT+BEEOJ+Zmt8xOdunB6nea2i7nBIDfSiRIKmR+CH541IlY3F7HzMXeKbHc+vImXPc3pW5v0nj/RttbA6LZ0y2Lr02heyP+WKvHIWsJlgNXtHsU6lNPI8AXm2yyJgaQwQwIPocBPr6FOTSvqPJjLS6t5Qr9QoOxq27UM4nYa4efWWmEXlMfGvK9yuKk5IKd4u1fV3lsIiQn3B2OIl6xNmjGaLQPyXJs4qpYuORxMqIGaqD+7eEW0gZmuAp9s/992LRd9APoQTaZayWdsR7ysc7Rc6pUODzSZJyBhsr8SQqotEWxcHDyRUxkwgWaPmlxbtbQXiobDD0EMwqlNgVtaAqZoUCd5s10U13MfsK0S/yUH/fz/VZF+i0Y5jszvpxbDDjQou+fj+k6gMGtTv8+a1a4SujaeqViO0ZjbcjP6aDbB0P6NCMcavje9HnR691/KZhXrkf7iOjADzW1el90o6H/Ct9B/jQUsB8dA5B/zxGVE03O3mDMwLeQGuLJulrlIbVdCNimvHmAXYYpAadPZEpZkDfOg6/0ris4EIcfbpRniUV5w/rRHPrQ8xrWGS3FK49czOe9LkNQwGlye62qE2ItUfxot0Qm38yWrhuakVzhDeqbE1AKrKsRzR3I94rbH3/TomfnWuYVRWUlQimCHxJBJHFqrLKKepHoWznWVsYeza3YiWuw==
  template:
    metadata:
      creationTimestamp: null
      name: aws-secret
      namespace: default
    type: Opaqueclear
