apiVersion: v1
kind: Service
metadata:
  name: game-2048
  namespace: main-fpt
  annotations:
    alb.ingress.kubernetes.io/target-type: ip
spec:
  type: NodePort
  selector:
    app: game-2048
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: main-fpt
  annotations:
    alb.ingress.kubernetes.io/target-type: ip
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 5000
    protocol: TCP