---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-secret
  namespace: main-fpt
spec:
  encryptedData:
    access-key-id: AgAhV7A1AhkWVrW75TAdxGUHdKJOnyYVnSBXQo4Tdp1/QCm/3Wcq2c/qRwTXJcTDHZAbrKZGc4enR3SXeaSdQWS1HLqtLUzDZcFFljTPcz8IYSjhqklupcP86yRwhjyRDqdewC6u4LJxh8KDhw5gEOxa5Hbcm0iN4W17tKIxDoLhJ+UOQ3bliyf53tUoeBKfrFJhSK195sdk2MIWhwtVYxyxyJdoeUQ0kgwupSzVu7OdfqATiAOvFYuFlVCk6RxxHq/Yr/WROgAs2G5HUp9xw/+o6RChgxp1kNXa5TBgJq9BykN4YyQH35tpZGyUM+imv9Ur/uxhg9cOtLkC0iDNKpNU3YI4iBIU4oC6gV5NLbFht7dVgB/NB6r753YM6lyAoF14l/tWM9jd4NCp6j9dZHxYyKtuC2H8si5CT2iC1Yl+ldSixInpNB7prVrjfJPC7bUYMsVXB5WqndehkNeV5MwN4uOMxVMoW9HrHIrYFbZmFug+/iGUp1WLvBornh4LDyYIdtBM/W+MuV8mqRG9lvmmt76J+3kqtXWrWVCzeOe+E2oDypDeu8wO9N4bllJ4jeLn1gac7V8D7M8YY6RsU75gLUWuAdyDPAtoq2T0UdeUPlgc/mrouxVZsaA6exvG1IeaQw9v1ElRq9qskvfKSwQlj26fo1JilmFwLdMzPXWALjA8QQW759XEHqIRwKZZyq6T0PfJLIMY/ucC8MXTCDxoEOYYPBQ=
    secret-access-key: AgAG68PgSHDOWQTieq65917W6PWTJQDfx/hXvJQxBo/5iCin9WbIvdYGNAPerhqe42Wj401SC4OU4pijh3O2WidCxA57kzoEAKgELbM6geJpabLXApFNCVdthkFURakT0lgHZTBQrdZ29RnrYWceJPrrjY8PWKzOtjykoKOwtOj8LbGIfK2NTAh19NJbMgcfiBIGAdWoCDW1rrd03J2Fy0A9FbKyLlkcwz0DfdKKT1mci5lEVSGJEBaKyKTCVTtftIk9QEYmWYaGEDAknwnShghSEkZJa4BBETJ9ksr49v93aEOKh2zTvcsBuKHx94WbXgs0zKNTCsqNKRxF+PWW2hhzY09RQQsEDheprut2NR6noM0RZXE8kx+EOQ7KOzRoORs3eGCjemO5h9o3R4hNF2y+mDDW66cjbf5I8IFqY2Mn34t31VCf5+x/K63VidTSn5oIHyvc2d//Rj95Fm5AVNpsCOF1xCSbpKzEmpLc5jVzPdr9mSHFVxc+3diIRysOtpHlkJDozxHPGNh5qeJQr4NYAw878Tv9be514owC5tn1W/Tj9ElowjyfPmGNxDxBZevL1YetViwEznoPZIwWhfGXLurYLQvOvY1cckHxoFuyAtUuMvZt8N5aLHm4RRqk8cRSEQrZqvZe2659jRNuQhvbE8Tncy1S8eiErhuVBsjw9Nu30WzdErsSn25OB/ro8qlDBpxNFGY99mkqqqQ7eLc6ZScmYtle+T7dzW7zP8Zs42wBKpUbGrDcvQ==
  template:
    metadata:
      creationTimestamp: null
      name: aws-secret
      namespace: main-fpt
    type: Opaqueclear
