apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-2048
  namespace: main-fpt

spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.game.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.game.label }}
    spec:
      containers:
      - name: game-2048
        image: amigoscode/2048
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: main-fpt

spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.fpt.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.fpt.label }}
    spec:
      containers:
      - name: fpt-flask-redis-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /health
            port: 5000  # Port inside the container where the application is listening
          initialDelaySeconds: 10
          periodSeconds: 30
        imagePullPolicy: Always
        imagePullSecrets:
          - name: aws-secret
