apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secretstore
  namespace: main-fpt
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-secret-cred
            key: access-key-id
          secretAccessKeySecretRef:
            name: aws-secret-cred
            key: secret-access-key
