{{- range .Values.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  namespace: main-fpt
  annotations:
    alb.ingress.kubernetes.io/target-type: ip
spec:
  type: NodePort
  selector:
    app: {{ .label }}
  ports:
  - port: {{ .port }}
    targetPort: {{ .targetPort }}
    protocol: TCP
---
{{- end }}
